import logging
import os
from typing import Any, Dict, Generator, List, Optional

import streamlit as st

logger = logging.getLogger("CampusGPT.llm_local")

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS_DIR = os.path.join(BASE_DIR, "models")
os.makedirs(MODELS_DIR, exist_ok=True)

# Safe imports for Llama
LLAMA_AVAILABLE = False
try:
    from llama_cpp import Llama

    LLAMA_AVAILABLE = True
    logger.info("llama-cpp-python is available and successfully imported.")
except ImportError:
    logger.warning("llama-cpp-python is not installed. Local LLM capabilities will be disabled.")


def is_llama_available() -> bool:
    """Returns True if llama-cpp-python can be successfully used."""
    return LLAMA_AVAILABLE


def get_installed_gguf_models() -> List[Dict[str, Any]]:
    """Scans the models/ directory for installed GGUF files and maps their metadata.

    Returns:
        List[Dict[str, Any]]: A list of dictionaries representing GGUF models.
    """
    models: List[Dict[str, Any]] = []
    if not os.path.exists(MODELS_DIR):
        return models

    for file in os.listdir(MODELS_DIR):
        if file.lower().endswith(".gguf"):
            file_path = os.path.join(MODELS_DIR, file)
            size_bytes = os.path.getsize(file_path)
            size_gb = size_bytes / (1024 * 1024 * 1024)

            # Map heuristics for context length and display names
            name_lower = file.lower()
            context_len = 2048  # Default context window fallback
            display_name = file.replace(".gguf", "").replace("-", " ").title()

            if "qwen" in name_lower:
                context_len = 32768
                display_name = "Qwen 3 Instruct GGUF"
            elif "gemma" in name_lower:
                context_len = 8192
                display_name = "Gemma 3 IT GGUF"
            elif "phi" in name_lower:
                context_len = 4096
                display_name = "Phi-4 Mini GGUF"
            elif "mistral" in name_lower:
                context_len = 8192
                display_name = "Mistral 7B Instruct GGUF"

            # Estimate RAM overhead (file size + ~1.2GB for context and runtime allocations)
            ram_estimate_gb = size_gb + 1.2

            models.append(
                {
                    "filename": file,
                    "filepath": file_path,
                    "display_name": display_name,
                    "size_gb": f"{size_gb:.2f} GB",
                    "context_len": context_len,
                    "ram_estimate": f"{ram_estimate_gb:.1f} GB",
                }
            )

    return models


@st.cache_resource
def get_cached_local_llm(model_filename: str, context_len: int = 2048) -> Any:
    """Loads and caches the local GGUF model in memory using st.cache_resource.

    Args:
        model_filename (str): The filename of the GGUF model in the models/ folder.
        context_len (int): Context window length.

    Returns:
        Llama: The Llama-cpp client.
    """
    if not LLAMA_AVAILABLE:
        raise ImportError("llama-cpp-python is not installed and GGUF loading is disabled.")

    model_path = os.path.join(MODELS_DIR, model_filename)
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model file not found at: {model_path}")

    logger.info(f"Lazy loading GGUF model into memory: {model_filename} (context_len={context_len})")

    # Initialize Llama CPP flat binding
    # Set n_ctx to accommodate document text chunks
    llm = Llama(model_path=model_path, n_ctx=context_len, n_threads=os.cpu_count() or 4, verbose=False)
    logger.info(f"Model {model_filename} loaded successfully.")
    return llm


def generate_local_response_stream(
    prompt: str, model_filename: str, system_prompt: Optional[str] = None, context_len: int = 2048
) -> Generator[str, None, None]:
    """Yields streaming chunks of text generated by the local GGUF model.

    Args:
        prompt (str): Prompt to send.
        model_filename (str): Path of the local GGUF file in models/.
        system_prompt (str): System prompt.
        context_len (int): Context window.

    Yields:
        Generator[str, None, None]: Generated tokens.
    """
    try:
        llm = get_cached_local_llm(model_filename, context_len)

        # Formulate chat format based on prompt style
        formatted_prompt = ""

        if system_prompt:
            # We use standard ChatML template for prompt structure (supported by Qwen, Gemma, Phi)
            formatted_prompt += f"<|im_start|>system\n{system_prompt}<|im_end|>\n"
            formatted_prompt += f"<|im_start|>user\n{prompt}<|im_end|>\n"
            formatted_prompt += "<|im_start|>assistant\n"
        else:
            formatted_prompt = f"User: {prompt}\n\nAssistant: "

        logger.info(f"Running inference on GGUF model {model_filename}...")

        response_stream = llm(
            prompt=formatted_prompt,
            max_tokens=1024,
            temperature=0.1,  # Low temperature for factual compliance
            stream=True,
        )

        for chunk in response_stream:
            text = chunk["choices"][0]["text"]
            yield text

    except Exception as e:
        logger.error(f"Local inference generation error: {str(e)}")
        yield f"\n❌ Local model inference error: {str(e)}"
