repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports]
        exclude: ^(validate_project\.py|scripts/.*)

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [-c, pyproject.toml, -r]
        additional_dependencies: [toml]

  - repo: local
    hooks:
      - id: vulture
        name: vulture
        entry: vulture
        language: system
        pass_filenames: false
        always_run: true
      - id: semgrep
        name: semgrep
        entry: semgrep scan --config auto --error --quiet modules/
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]

  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.2
    hooks:
      - id: pip-audit
        args: [--local]

