[mypy]
python_version = 3.13
ignore_missing_imports = True
warn_unused_configs = True
strict_optional = True
check_untyped_defs = True
disallow_untyped_decorators = False
warn_redundant_casts = True
warn_unused_ignores = True
show_error_codes = True
exclude = (?x)(
    ^pages/
    |^tests/
    |^create_samples\.py
  )
